### ISSUE TITLE
loading projects doesn't work

### ISSUE THREAD

**Issue by MingleiYang** [fjossinet/RNArtist#11]
Hi,

when i tried to load the previous project, the error happened,

```
kotlin.UninitializedPropertyAccessException: lateinit property connectedJunction has not been initialized
	at rnartistcore@0.2.17-SNAPSHOT/io.github.fjossinet.rnartist.core.model.JunctionDrawing.update(Drawings.kt:2567)
	at rnartistcore@0.2.17-SNAPSHOT/io.github.fjossinet.rnartist.core.model.JunctionDrawing.setCurrentLayout(Drawings.kt:2221)
	at rnartistcore@0.2.17-SNAPSHOT/io.github.fjossinet.rnartist.core.io.ParsersKt.parseProject(parsers.kt:431)
	at rnartistcore@0.2.17-SNAPSHOT/io.github.fjossinet.rnartist.core.io.ParsersKt.parseJSON(parsers.kt:412)
	at rnartist@1.0/io.github.fjossinet.rnartist.io.EmbeddedDB.getProject(EmbeddedDB.kt:28)
	at rnartist@1.0/io.github.fjossinet.rnartist.gui.ProjectsPanel$ProjectCell$2$loadData$1.call(ProjectsPanel.kt:218)
	at rnartist@1.0/io.github.fjossinet.rnartist.gui.ProjectsPanel$ProjectCell$2$loadData$1.call(ProjectsPanel.kt:215)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Task.java:1426)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

and I also noticed that at the console, the error information of this showed up:

```
[INFO] --- exec-maven-plugin:3.0.0:exec (default-cli) @ rnartist ---
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

```

Thank you very much,

My best,

**Comment by fjossinet** [comment]
Hi.
The message in the console is not a problem. At now, I'm not using this log lib. Concerning your issue, i had quite the same this morning and i fixed it. Not sure if your issue is related. Could you get the last commit for RNArtist and clean package?

Let me know

**Comment by MingleiYang** [comment]
Hi, I tried the "mvn clean package exec:exec". however, The issue is still there. 

It was weird since it worked well before 10 clock. However, all of a sudden, it doesn't work.

My best,

**Comment by fjossinet** [comment]
You mean this morning? When did you update your RNArtist the last time before the issue?

**Comment by fjossinet** [comment]
I can test it on my side. What you can do is to zip and send me your .rnartist folder located in your home directory.

**Comment by fjossinet** [comment]
Hi. 

I have updated RNArtist. When you launch it, it asks you to choose a projects folder. Then it will move the projects in the embedded database into this folder. For each project, you will get a preview as a PNG and the data as a script using the RNArtistCore language. This is a basic conversion, only the 2D structure and the layout are targeted. The theme is not converted but you can easily get a new one with the RNArtist GUI. 

Does this conversion fix this issue?

Best

**Comment by fjossinet** [comment]
Hi. Did you install the last version from this page: https://www.jdeploy.com/~rnartist

Could you give it a try because many things have been modified and fixed. Thanks
